######################################################################
# Automatically generated by qmake (2.01a) Fri May 30 12:09:49 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += \
    draganddrop/*.h

SOURCES += \
    draganddrop/*.cpp
