######################################################################
# Automatically generated by qmake (2.01a) Mon Jun 30 19:30:26 2014
######################################################################

TEMPLATE = app
TARGET = testrunner
DEPENDPATH += .
INCLUDEPATH += .
INCLUDEPATH += ..


CONFIG += qt
QT+=sql core xml widgets printsupport network


# Input
SOURCES += $$system(ls *.cpp)

HEADERS += $$system(ls *.h)


LIBS     +=  -lgui -lservices  -ldatamodel  -lklfbackend -lorm
LIBS     += -lpoppler-qt5

QMAKE_LIBDIR += -L/usr/lib
QMAKE_LIBDIR += $$OUT_PWD/../gui
QMAKE_LIBDIR += $$OUT_PWD/../orm
QMAKE_LIBDIR += $$OUT_PWD/../datamodel
QMAKE_LIBDIR += $$OUT_PWD/../services
QMAKE_LIBDIR += $$OUT_PWD/../klfbackend
