######################################################################
# Automatically generated by qmake (2.01a) Mon Jun 30 19:30:26 2014
######################################################################

TEMPLATE = app
TARGET = testrunner
DEPENDPATH += .
INCLUDEPATH += .
INCLUDEPATH += ..
INCLUDEPATH += ../ /usr/include/KDE

CONFIG += qt
QT+=sql


# Input
HEADERS += testcase.h \
           testindirectrepositoryproperty.h \
           testklasse.h \
           testobserver.h \
           testqdatetime.h \
           testreadcsvlistaction.h \
           testrunner.h \
           testsitzplan.h \
           testskalender.h \
           testsstundenplan.h \
           teststunde.h \
           teststundenplantemplateeintrag.h \
    testlektuere.h
SOURCES += testcase.cpp \
           testindirectrepositoryproperty.cpp \
           testklasse.cpp \
           testobserver.cpp \
           testqdatetime.cpp \
           testreadcsvlistaction.cpp \
           testrunner.cpp \
           testsitzplan.cpp \
           testskalender.cpp \
           testsstundenplan.cpp \
           teststunde.cpp \
           teststundenplantemplateeintrag.cpp \
    testlektuere.cpp


LIBS     += -lkdeui
LIBS     += -lkdecore
LIBS     += -lkio
LIBS     += -lkparts
LIBS     += -lpoppler-qt4
LIBS     += -lpdfview

#release {
#LIBS     += -L/home/mopp/dev/stundenplaner-build-desktop-Qt_4_8_1_in_PATH__System__Release/gui -lgui
#LIBS     += -L/home/mopp/dev/stundenplaner-build-desktop-Qt_4_8_1_in_PATH__System__Release/orm -lorm
#LIBS     += -L/home/mopp/dev/stundenplaner-build-desktop-Qt_4_8_1_in_PATH__System__Release/datamodel -ldatamodel
#LIBS     += -L/home/mopp/dev/stundenplaner-build-desktop-Qt_4_8_1_in_PATH__System__Release/services -lservices
#}

debug {
LIBS     += -L/home/mopp/dev/stundenplaner-build-desktop-Qt_4_8_1_in_PATH__System__Debug/gui -lgui
LIBS     += -L/home/mopp/dev/stundenplaner-build-desktop-Qt_4_8_1_in_PATH__System__Debug/orm -lorm
LIBS     += -L/home/mopp/dev/stundenplaner-build-desktop-Qt_4_8_1_in_PATH__System__Debug/datamodel -ldatamodel
LIBS     += -L/home/mopp/dev/stundenplaner-build-desktop-Qt_4_8_1_in_PATH__System__Debug/services -lservices
}
LIBS     += -L/usr/lib
