######################################################################
# Automatically generated by qmake (2.01a) Thu Jun 26 20:01:04 2014
######################################################################

TEMPLATE = app
TARGET = mappinggenerator
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mappinggenerator.h
SOURCES += mappinggenerator.cpp



CONFIG += qt
QT+=sql widgets xml
